### PR TITLE
#172 - Ensure csrf cookie on `CreateEventSchedule`

### LINKED ISSUE #172: CSRF error when adding activity
When I try to create a new activity, after filling the fields and pressing the 'Submit' button, the error 'CSRF Failed: CSRF cookie not set.' is displayed.

I tried to execute the same procedure on production environment (speakerfight.com) and got the same error.

Exact steps to reproduce:

1. Login into speakerfight
2. Click `New Event`
3. Fill the form and submit
4. Click `Create Schedule`
5. Cllick `Add Activity`
6. Fill the form and submit

### PR DESCRIPTION
**Pull request by meiralins**
Fixes #172 
Let me know if you need something more @luanfonceca

### CODE REVIEW

**Comment by meiralins** [comment]
@mauricioabreu , thanks for the reply.
I don't quite understand what you said, so I think it's possible you missread the function I used.
I used the [ensure_csrf_cookie ](https://docs.djangoproject.com/pt-br/1.10/ref/csrf/#django.views.decorators.csrf.ensure_csrf_cookie). This function simply forces the view to send the CSRF cookie.

**Comment by mauricioabreu** [comment]
@meiralins could it be solved by setting the CSRF middleware and adding the csrf_token template tag inside the HTML?

**Comment by meiralins** [comment]
Hey, now I understand what's going on. I didn't realize the CSRF middleware was disabled as the csrf_token template tag is used everywhere. I agree with your first comment.

Clearly this PR is not an acceptable solution so I will close it and we can continue the discussion in #172 .

**Comment by mauricioabreu** [comment]
I am not 100% against your solution. It will work and you did a good job.
Otherwise Django itself does not recommend ensure token by views. :(

**Pull request closed without merging**
