### PR TITLE
Improving the design of long proposals when collapsed

### LINKED ISSUE #167: Collapse long proposal design error
Hey folks,

I know that you have implemented the new design for the proposal, allowing big proposals to stay short. The problem is that it's not clear when the proposal is shortened or not, so I suggest you to do some signaling or anything like that letting the user know when the proposal he is reading is collapsed.

### PR DESCRIPTION
**Pull request by wagnerluis1982**
- Now a "Show more" link is displayed
- Avoid to collapse proposals only a few pixels longer

Fixes #167

### CODE REVIEW

**Comment by wagnerluis1982** [comment]
I made some rebase, but is now done!

**Comment by tarsisazevedo** [comment]
There is a way to collapse a proposal that was expanded?

**Comment by wagnerluis1982** [comment]
@tarsisazevedo, there is no way to collapse again, only by refreshing!

I think would be ugly a explicit "Hide text" link in the end of each proposal. I gave other reasons in my comments on #167.

**Comment by luanfonceca** [comment]
@tarsisazevedo i asked him to not do the collapse back action.

**Comment by wagnerluis1982** [comment]
Hello, this PR will get approval?

**Comment by luanfonceca** [comment]
@wagnerluis1982 there are a pending review on the https://github.com/luanfonceca/speakerfight/pull/181/files 

screen shot 2016-10-27 at 5 01 06 pm

**Comment by wagnerluis1982** [comment]
Curiosity: why the review came as a screenshot? This is normal on GitHub?

**Comment by wagnerluis1982** [comment]
@luanfonceca, I tried to put JS `gettext` as

```javascript
self.after("<div class='show-more'><a>" + gettext('Show more') + "</a></div>");
```

but when I call `makemessages -l pt_BR`, the string is not added to **.po** file. It was due to this that I opted to use `{% trans ...}`.

I'm not sure why the string isn't considered but I guess that's because it is in a template file, not in a static javascript file.

**Comment by luanfonceca** [comment]
I just remembered that you need to run a different command:

`python manage.py makemessages -d djangojs --all`
It will look up on the djangojs domain and create all the translations messages, after that you will open the `djangojs.po` in the poedit like you did with the `django.po`.

**Comment by wagnerluis1982** [comment]
@luanfonceca I discovered that `makemessages` doesn't take in consideration calls to JS `gettext` inside templates. If I add an entry manually to the `djangojs.po`, the translation works, but in the next call to `makemessages` the entry will be removed.

Then, it seems the only way is to move the code to an external JS file. May I do?

**Pull request merged**
