### PR TITLE
Anonymous Voting

### PR DESCRIPTION
**Pull request by berinhard**
This PR address issue #139 

cc/ @renatooliveira @fjsj @mauricioabreu

### CODE REVIEW

**Comment by berinhard** [comment]
I guess we can't think on a better way to communicate better at 2 pages:

- Event creation: for now, it's just a checkbox with the text next to it, but it doesn't seemed so self-explanatory for me. Maybe we could add a help text for this field;
- Event detail: maybe we could add a disclaimer explaining why the name and pictures of the speakers aren't showing;

**Comment by berinhard** [comment]
@mauricioabreu or @renatooliveira I need feedback on this PR.

**Comment by mauricioabreu** [comment]
Going to review it soon.

**Comment by luanfonceca** [comment]
@berinhard did you already see how the Jury works?
In there we can invite people to become part of the jury of an event, in there i just ask for the email and if exists a user with that email we connect with the event and send a email to him, i think that we can do same in here.

Thanks <3

**Comment by mauricioabreu** [comment]
About the code and implementation: :+1: 
Can you add a test for this feature?

**Comment by tarsisazevedo** [comment]
Code lgtm.
About event help text: 👍

**Comment by luanfonceca** [comment]
Hey @berinhard i think we should do something like this in the Event detail.

screen shot 2016-09-11 at 9 02 36 pm


```diff
diff --git a/deck/templates/event/event_detail.html b/deck/templates/event/event_detail.html
index ebe73b1..e6c0b29 100644
--- a/deck/templates/event/event_detail.html
+++ b/deck/templates/event/event_detail.html
@@ -41,6 +41,17 @@
     </div>
     {% endif %}
 
+    {% if not event.anonymous_voting %}
+    <div class="col-md-12">
+      <div class="alert alert-warning">
+        <i class="icon-eye-close"></i>
+        {% blocktrans %}
+          This event is in the <strong>Anonymous Voting</strong> mode, all the speakers are hidden for voting, you should base your vote just in the content of the proposals.
+        {% endblocktrans %}
+      </div>
+    </div>
+    {% endif %}
+
     <div class="col-md-10 col-md-offset-1">
       <div class="event-proposals-header">
         {% if event.due_date_is_passed %}
```

**Comment by luanfonceca** [comment]
@berinhard i will code and merge this with my modifications ok?!

<3

**Comment by luanfonceca** [comment]
@berinhard Is just deploy, it is working like a charm, thanks for this i hope a lots of people use it
o/

screen shot 2016-09-16 at 6 01 18 pm

**Pull request merged**
