### PR TITLE
Fix issue #69

### PR DESCRIPTION
**Pull request by pgrangeiro**
Issue: Password reset template does not show error messages.
Fix: Add form field errors treatment in password reset template.

captura de tela de 2016-12-13 01-19-19

### CODE REVIEW

**Comment by mauricioabreu** [comment]
Hey @pgrangeiro good work. :)

I have some considerations you would like to read:

1 - Tests are failing BUT it is not your fault. @luanfonceca did you change something in the build process? It looks like some keys are wrong.
2 - You can go further and implement a generic stuff like it: https://docs.djangoproject.com/en/1.10/topics/forms/#reusable-form-templates

What do you think?

Anyway, thanks for your pull request.

**Comment by pgrangeiro** [comment]
Hi @mauricioabreu 

1- Yeah! I saw that :)
2- Sure! Do you think is better to implement this feature in this PR or in another one? (Whereas I have to check all templates that have forms to replace by this include)

Cheers,

**Comment by mauricioabreu** [comment]
@pgrangeiro cool!
Well, do as you please 😄 . If want to open another PR, go ahead. If you don't, go ahead too. haha

**Comment by mauricioabreu** [comment]
Sorry but I just sounded like Bane:

bane

"Do as you please..."

**Comment by pgrangeiro** [comment]
Haha

Alright then. I going to close this PR and open a new one.

**Pull request closed without merging**
