### PR TITLE
WIP - Upgrade to django 1.10 and Python 3

### PR DESCRIPTION
**Pull request by luzfcb**
I will work on it in my spare time ... it should take a long time to finish
- [x] make all tests pass successfully
- [x] fix all django 1.7 to django 1.10 compatibility problems
- [x] update all dependencies to pytho3 compatible versions
- [x] fix all deprecation warnings (`python -Wall manage.py test -v 2`)
- [x] check missing migrations (`python manage.py makemigrations --dry-run --check`)
- [ ] check if works on production environment
- [x] Enable https://pyup.io to automatic send pull-request when a new version of any Python dependencies is release. (demo https://github.com/pydanny/cookiecutter-django/pull/1287 )

related to https://github.com/luanfonceca/speakerfight/issues/129

### CODE REVIEW

**Comment by luanfonceca** [comment]
Did you check if our dependencies works on py3? Like fabric, uwsgi...

**Comment by luanfonceca** [comment]
I think that just django goes up to 1.10 is far than good for this PR @luzfcb

**Comment by luzfcb** [comment]
@luanfonceca 
fabric has a fork with python3 support: https://github.com/mathiasertl/fabric/
uwsgi has a Python3 classifiers https://github.com/unbit/uwsgi/blob/master/setup.py#L127

said this, all dependencies install in Python 3, and the tests are run successfully: https://travis-ci.org/luanfonceca/speakerfight/builds/171300756

I avoided the maximum to update the dependencies, focusing first on making the tests pass. update the dependencies will be a later stage

the tests are failing now because there are migrations that were not created / updated for some reason

**Comment by luanfonceca** [comment]
@luzfcb Are you still working on this?

**Comment by luzfcb** [comment]
@luanfonceca I completely forgot about this pull-request. I probably will not have free time in the next few weeks to finish this. Sorry.

**Comment by luanfonceca** [comment]
What changes do i need to do in order to upgrade just the Django to 1.11 and keep the Python 2 for now?

**Pull request merged**
