### PR TITLE
Implementation for issue #148: Make the deadline more visible 

### PR DESCRIPTION
**Pull request by vctrmagno**
Due date is highlighted now. 
If current date is close to the due date, the last one is displayed in a tone of red.

### CODE REVIEW

**Comment by luanfonceca** [comment]
Can you add a print?

**Comment by vctrmagno** [comment]
Current date < (due date - 7 days)
due-date

Current date > (due date - 7 days)
due-date-close

**Comment by vctrmagno** [comment]
If you don't like the the style nor the rule, at least it is simple to change it now.

**Comment by luanfonceca** [comment]
I think the `text-warning` and `text-danger` are simplier (you can use a `{% if %}` inside the span class instead of duplicate all the html) and their color schemes are already known for everyone, which improves the ux

**Comment by vctrmagno** [comment]
Sure. I'll do it and send another PR.

**Comment by luanfonceca** [comment]
you dont need to send another, just commit on the same branch

**Comment by luanfonceca** [comment]
Another thing, if you can explain me how it will works. Like when it will be yellow or red, based on what. o/

**Comment by vctrmagno** [comment]
I just created a property called due_date_is_close that returns a bool if the current date > due_date - 7days. If the left time is minor that 7 days it is displayed in red (text-danger), else it is displayed in yellow (text-warning).

**Comment by luanfonceca** [comment]
Nice @vctrmagno, i will merge and deploy this!

But first i would ask for you to revert the last commit, it doesn`t have any reason to be in this PR, it is a solution for other problem and will generate a conflict when i try to merge your code.

**Comment by luanfonceca** [comment]
Your contribution was deployed!

http://speakerfight.com/events/poticon-1a-conferencia-potiguar-de-software-livre/
screen shot 2016-10-18 at 5 05 52 pm

**Comment by vctrmagno** [comment]
Great, @luanfonceca. Now I'm more acquainted with the project, in the next contributions the process will be smoother. Do you still want a revert on that commit?

**Comment by luanfonceca** [comment]
Nope, i did it during the merge.

o/

**Pull request merged**
