### PR TITLE
Implementing the #65 enhancement. 

### PR DESCRIPTION
**Pull request by felipevolpone**
I intercepted the user_signed_up Signal from Django-AllAuth and use it to send an welcome message to the user. You can check the message in deck/templates/mailing/welcome.txt

### CODE REVIEW

**Comment by felipevolpone** [comment]
The tests are ok, but the deploy is broken.

**Comment by luanfonceca** [comment]
Hi @felipevolpone, thanks for that.

If you look at the test code of the Event/Proposal creation notifications, you can find your way to test it: https://github.com/luanfonceca/speakerfight/blob/master/deck/tests/test_functional.py#L42 
You can see it and say to me if can be done, otherwise i will merge it right now. 

If you allow me, a good tip is not create pull-requests from your master branch (always create a new branch from the `master` to propose your PR), because until your code be merged, you will not be able to code anymore, because your repository will have some commits that doesn't exist on the "origin" source.

If you have any question you can reach us on our [Gitter](http://gitter.im/luanfonceca/speakerfight).

o/

**Comment by felipevolpone** [comment]
Thanks for the example, I'll write a test for the feature so. Also, I will close this PR to create it in another branch and send an PR again.

**Comment by luanfonceca** [comment]
Nice @felipevolpone.
o/

**Pull request closed without merging**
