### PR TITLE
Fix spelling in readme

### PR DESCRIPTION
**Pull request by vishalsodani**
Fix spelling and change the sentence structure.

### CODE REVIEW

**Comment by luanfonceca** [comment]
I will merge this after Oct 01 to count on your contributions for the hacktoberfest, okay? haha

**Comment by vishalsodani** [comment]
Haha :) Sure!

**Comment by luanfonceca** [comment]
Hi @vishalsodani, you need to generate the translation files.

Run the following commands:
`python mange.py makemessages --all` and `python mange.py compilemessages`

**Comment by vishalsodani** [comment]
@luanfonceca Does this project work with Python 2.7 or some other version?

**Comment by mauricioabreu** [comment]
@vishalsodani it is intended to work with Python 2.7 only. Maybe 2.6 but I did not give it a try yet.

**Comment by luanfonceca** [comment]
I think that today it only works with 2.7 and maybe 2.6.

With a small compatibility with python3 but i am not sure on that it will work and some dependencies too.

**Pull request merged**
