### PR TITLE
Fix Travis configuration

### PR DESCRIPTION
**Pull request by mauricioabreu**
Syntax fixed to deploy only the master branch.

### CODE REVIEW

**Comment by mauricioabreu** [comment]
I think we need the key you deleted in a previous commit.

**Comment by luanfonceca** [comment]
I think it is not fixed, because they are still executing the `fab deploy`, when you are in another branch.

https://travis-ci.org/luanfonceca/speakerfight/builds/76778874#L729

**Comment by mauricioabreu** [comment]
Ok, in this case, we can use de ```deploy```directive. :)
I will update this PR.

**Comment by mauricioabreu** [comment]
What about now? :-)

**Pull request merged**
