### PR TITLE
Group "My proposals" by event

### PR DESCRIPTION
**Pull request by mauricioabreu**

### CODE REVIEW

**Comment by mauricioabreu** [comment]
myproposals

**Comment by luanfonceca** [comment]
For this feasture i think in something like this, The same Event block that has in the events detail page, without the description and inside it the Proposals, using the same hierarchy that has in the events detail.

screen shot 2017-09-26 at 11 44 12


* Ignore the proposal action buttons, i was using the web dev tools to mock this

**Comment by mauricioabreu** [comment]
@luanfonceca it looks better. I will try this at home, thx

**Comment by mauricioabreu** [comment]
@luanfonceca done!

**Pull request merged**
