### PR TITLE
Make font sizes responsive in CTA button

### LINKED ISSUE #267: Responsive Call To Action button bugs
Beside its size is too exaggerate for the layout, if the text breaks to a new line the button doesn't follow it. So it should be nice if we change his layout to a simple one that works better in small screens.

screen shot 2017-09-28 at 17 52 02

### PR DESCRIPTION
**Pull request by lex111**
Fixes #267

### CODE REVIEW

**Comment by luanfonceca** [comment]
Hi @lex111, sorry for asking this, but can you take a look at other resolution as well and other places that uses this kind of button?

screen shot 2017-10-02 at 10 25 28
screen shot 2017-10-02 at 10 27 12


Thanks in advance.

**Comment by lex111** [comment]
@luanfonceca oops, the English version is all right, I just checked there. Strangely, I set the profile profile changed the language to Portuguese, but the main page was English, how did I change the language on the index page?

But in any case, since the length of the text depends not only on the screen size, but **also** on the language, you need some mechanism for determining what the text does not fit in one line... Or add new styles for the Portuguese language, which is much easier...

**Comment by luanfonceca** [comment]
Hi @lex111, thats why just change the `font-size` is not the better solution, in that cases the button usually grows together to fit the new lines.

To cover all the cases, we need to make the button follow the break-line and change the font-size for visually effect. We can't have a 300px screen with a text with font in 80px, right?

For me, the bug is that the button doesn't handle the "break-line", after that we have the font size improvements. Change the font-size is temporary solution, cause its depends on the text inside the button. The moment we change the text something may broke again.

**Comment by lex111** [comment]
We can prevent the breaking of lines, but then the text will not be displayed correctly, in one line always.

**Comment by luanfonceca** [comment]
The button needs to change his height in order to fit the text.

Something this:
screen shot 2017-10-02 at 11 57 14

**Comment by lex111** [comment]
Then do not change the font size? We just need to make the button change the height depending on the text?

**Comment by luanfonceca** [comment]
I think the best solution may be the both together, fix this break-line bug and if its necessary change the font-size.

Thanks in advance for everything @lex111 <3

**Comment by lex111** [comment]
@luanfonceca I made the changes, see how now. I still removed the responsive font sizes, because it's nowhere to be found, and I do not think it's necessary.

**Comment by luanfonceca** [comment]
Nice, i tested and everything looks fine. I just have a question about the 404 pages, it has a `.big-button` in there, i think we need to add the `.big-button-container` too, right?

**Comment by lex111** [comment]
@luanfonceca Yes, you're right, done :+1:

**Comment by luanfonceca** [comment]
I just deployed this, thanks for everything @lex111.

Sorry if i was a bit annoying about what solution is better or worse <3

**Comment by lex111** [comment]
Haha, everything was fine, I hope it was useful for you :smile:

**Comment by luanfonceca** [comment]
Of course you are, thats bugs with button was drive me crazy but it was a google first-time issue to Speakerfight, so i let someone else to close it.

**Pull request merged**
